GET http://localhost:5000/ganesh23suggestions HTTP/1.1
Content-Type: application/json

###

POST http://localhost:5000/ganesh23/addsuggestion HTTP/1.1
content-type: application/json

{
    "message": "Hi this is my suggestion 2",
    "timestamp ": "2023-09-04T18:30:00.000Z"
}

###
curl -X POST https://messages-sandbox.nexmo.com/v1/messages \
-u '4a2bc402:sSv14GQCc5ZZaXvB' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-d '{
    "from": "14157386102",
    "to": "919533943973",
    "message_type": "text",
    "text": "This is a WhatsApp Message sent from the Messages API",
    "channel": "whatsapp"
  }'